version: "3"

services:
  frontend: 
    build: ./client
    container_name: app_frontend
    ports: 
      - 3000:3000
    stdin_open: true

  backend: 
    build: ./
    container_name: app_backend
    ports:
      - 5000:5000